import {useEffect,useState} from 'react';
type Account={id?:string;username:string;role:string;active:boolean};
const blank:Account={username:'',role:'hr',active:true};
export default function AccountManager({onSaved}:{onSaved?:()=>Promise<void>}){
 const [accounts,setAccounts]=useState<Account[]>([]),[form,setForm]=useState<Account>(blank),[password,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/accounts',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error);setAccounts(b.accounts);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 return <main className="max-w-4xl mx-auto p-5 space-y-5"><h1 className="text-2xl font-bold">Dashboard accounts</h1><p className="text-sm text-slate-500">Reset passwords here. Existing passwords cannot be viewed. Changing an account signs it out on all devices.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-green-700">{message}</p>}<div className="overflow-x-auto border rounded-xl"><table className="w-full text-sm text-left"><thead><tr><th className="p-3">Username</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t"><td className="p-3">{a.username}</td><td>{a.role}</td><td>{a.active?'Active':'Disabled'}</td><td><button className="underline p-2" onClick={()=>{setForm(a);setPassword('');setMessage('');}}>Edit / reset password</button></td></tr>)}</tbody></table></div><form className="border rounded-xl p-5 space-y-4 max-w-md" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,...(password?{password}:{})})}),b=await r.json();if(!r.ok)throw Error(b.error);setForm(blank);setPassword('');setMessage('Account saved.');await onSaved?.();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2 className="font-semibold">{form.id?'Edit account':'Create account'}</h2><label className="block text-sm">Username<input className="block w-full border rounded p-2 mt-1" autoComplete="off" required pattern="[a-z0-9._-]{2,64}" value={form.username} onChange={e=>setForm({...form,username:e.target.value.toLowerCase()})}/></label><label className="block text-sm">Role<select className="block border p-2 mt-1 rounded w-full" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="admin">Admin — all records and accounts</option><option value="ceo">CEO — all leave records</option><option value="hr">HR — intern leave only</option></select></label><label className="block text-sm">{form.id?'New password (leave blank to keep current)':'Password'}<input className="block w-full border rounded p-2 mt-1" type="password" autoComplete="new-password" minLength={8} maxLength={128} required={!form.id} value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Account enabled</label><div className="flex gap-3"><button disabled={busy} className="rounded bg-slate-900 text-white px-4 py-2">{busy?'Saving…':'Save account'}</button><button type="button" onClick={()=>{setForm(blank);setPassword('');}}>New account</button></div></form></main>;
}
