import {useEffect,useState,useRef} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import CeoDashboard from '@/pages/CeoDashboard';
import InternDashboard from './InternDashboard';
import AccountManager from './AccountManager';
import DashboardHeader from './DashboardHeader';
import danPortrait from '@/image/dan-login.png';
import hrPortrait from '@/image/hr-login.png';
import tbsLogo from '@/image/TBS-Logo.png';
import CompanyCalendar from './CompanyCalendar';
import RegistrationReview from './RegistrationReview';
import {Users, GraduationCap, Settings, LogOut, ChevronDown} from 'lucide-react';
import {DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
type Session={id:string;username:string;role:'admin'|'ceo'|'hr'};
function clearLegacyRecords(){try{for(const key of Object.keys(localStorage))if(key.startsWith('tbs_employees_'))localStorage.removeItem(key);}catch{/* No stored records can be read by this dashboard. */}}
export default function DashboardAccess(){
 const client=useQueryClient(),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[view,setView]=useState('leave');
 const checkVersion=useRef(0);
 async function check(){const version=++checkVersion.current;try{const r=await fetch('/api/auth',{cache:'no-store'}),b=await r.json();if(version!==checkVersion.current)return;if(!r.ok)throw Error(b.error);setSession(old=>{if(old?.id!==b.session?.id||old?.role!==b.session?.role){client.clear();setView('leave');}return b.session??null;});setError('');}catch(e){if(version!==checkVersion.current)return;client.clear();setSession(null);setError((e as Error).message);}finally{if(version===checkVersion.current)setLoading(false);}}
 useEffect(()=>{clearLegacyRecords();void check();const id=setInterval(check,60000);window.addEventListener('focus',check);return()=>{clearInterval(id);window.removeEventListener('focus',check);checkVersion.current++;};},[]);
 if(loading)return <main className="p-12 text-center">Checking dashboard access…</main>;
 if(!session)return <main className="relative isolate min-h-screen overflow-hidden bg-slate-950 flex items-center justify-center p-5">
 <div aria-hidden="true" className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_left,_var(--tw-gradient-stops))] from-cyan-800 via-slate-900 to-slate-950"/>
 <div aria-hidden="true" className="pointer-events-none absolute inset-y-0 left-0 w-1/2 md:inset-0 md:w-auto -z-10 opacity-20 md:opacity-80 bg-contain md:bg-[length:auto_94%]" style={{backgroundImage:`url(${danPortrait})`,backgroundRepeat:'no-repeat',backgroundPosition:'left bottom'}}/>
 <div aria-hidden="true" className="pointer-events-none absolute inset-y-0 right-0 w-1/2 md:inset-0 md:w-auto -z-10 opacity-20 md:opacity-80 bg-contain md:bg-[length:auto_94%]" style={{backgroundImage:`url(${hrPortrait})`,backgroundRepeat:'no-repeat',backgroundPosition:'right bottom'}}/>
 <div aria-hidden="true" className="pointer-events-none absolute inset-0 -z-10 bg-gradient-to-r from-transparent via-slate-950/25 to-transparent"/>
 <form className="w-full max-w-xl self-center rounded-3xl bg-white p-8 sm:p-14 space-y-7 shadow-2xl" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),b=await r.json();if(!r.ok)throw Error(b.error);setPassword('');client.clear();await check();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="flex items-center gap-3 pb-5 border-b border-slate-100"><img src={tbsLogo} alt="TBS" className="h-14 w-auto"/></div><label className="block text-base font-medium">Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} className="mt-2 w-full border border-slate-200 rounded-xl p-4 text-lg focus:outline-none focus:ring-2 focus:ring-cyan-500"/></label><label className="block text-base font-medium">Password<input type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full border border-slate-200 rounded-xl p-4 text-lg focus:outline-none focus:ring-2 focus:ring-cyan-500"/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-cyan-600 hover:bg-cyan-700 font-semibold text-lg text-white p-4 disabled:opacity-50">{busy?'Signing in…':'Sign in'}</button></form></main>;
 const activeView=view==='holidays'?'holidays':session.role==='hr'?'interns':view;
 const navigation=<nav aria-label="Employee group" className="flex gap-1 rounded-xl bg-slate-800/80 p-1">
  {(session.role==='hr'?[{id:'interns',label:'Interns',Icon:GraduationCap}]:[{id:'leave',label:'Full-time',Icon:Users},{id:'interns',label:'Interns',Icon:GraduationCap}]).map(({id,label,Icon})=><button key={id} aria-pressed={activeView===id} onClick={()=>setView(id)} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300 ${activeView===id?'bg-cyan-500 text-slate-950 shadow-sm':'text-slate-300 hover:bg-slate-700 hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>)}
 </nav>;
 const account=<DropdownMenu><DropdownMenuTrigger asChild><button className="flex h-9 items-center gap-2 rounded-lg px-2.5 text-sm font-semibold text-slate-200 transition-colors hover:bg-slate-800 hover:text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-400 data-[state=open]:bg-slate-800" aria-label="Account menu"><span className="max-w-28 truncate">{session.username.toLowerCase()===session.role ? ({admin:'Admin',ceo:'CEO',hr:'HR'}[session.role]) : session.username}</span><ChevronDown className="h-3.5 w-3.5 text-slate-400" aria-hidden="true"/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel><span className="block">{session.username}</span><span className="text-xs font-normal text-slate-500">{{admin:"Administrator",ceo:"CEO",hr:"HR · Intern access"}[session.role]}</span></DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>setView('holidays')}>Company holidays</DropdownMenuItem>{session.role!=='hr'&&<DropdownMenuItem onSelect={()=>setView('registrations')}>Review registrations</DropdownMenuItem>}{session.role==='admin'&&<DropdownMenuItem onSelect={()=>setView('accounts')}><Settings className="mr-2 h-4 w-4"/>Manage accounts</DropdownMenuItem>}<DropdownMenuItem disabled={busy} onSelect={async()=>{checkVersion.current++;setBusy(true);try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw Error('Sign out failed. Please retry.');client.clear();clearLegacyRecords();setSession(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><LogOut className="mr-2 h-4 w-4"/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
 return <div className="min-h-screen bg-slate-100 text-slate-900">{error&&<p role="alert" className="bg-red-50 px-5 py-2 text-sm text-red-700">{error}</p>}{activeView==='leave'?<CeoDashboard navigation={navigation} account={account}/>:<><DashboardHeader navigation={navigation} account={account}/>{activeView==='holidays'?<div className="max-w-4xl mx-auto p-6"><CompanyCalendar/></div>:activeView==='registrations'&&session.role!=='hr'?<div className="max-w-4xl mx-auto p-6"><RegistrationReview/></div>:activeView==='accounts'&&session.role==='admin'?<AccountManager onSaved={check}/>:<InternDashboard canClassify={session.role!=='hr'}/>}</>}</div>;
}
