import {useEffect,useState,useRef} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import CeoDashboard from '@/pages/CeoDashboard';
import InternDashboard from './InternDashboard';
import AccountManager from './AccountManager';
import DashboardHeader from './DashboardHeader';
import {Users, GraduationCap, Settings, LogOut, ChevronDown} from 'lucide-react';
import {DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
type Session={id:string;username:string;role:'admin'|'ceo'|'hr'};
function clearLegacyRecords(){try{for(const key of Object.keys(localStorage))if(key.startsWith('tbs_employees_'))localStorage.removeItem(key);}catch{/* No stored records can be read by this dashboard. */}}
export default function DashboardAccess(){
 const client=useQueryClient(),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[view,setView]=useState('leave');
 const checkVersion=useRef(0);
 async function check(){const version=++checkVersion.current;try{const r=await fetch('/api/auth',{cache:'no-store'}),b=await r.json();if(version!==checkVersion.current)return;if(!r.ok)throw Error(b.error);setSession(old=>{if(old?.id!==b.session?.id||old?.role!==b.session?.role){client.clear();setView('leave');}return b.session??null;});setError('');}catch(e){if(version!==checkVersion.current)return;client.clear();setSession(null);setError((e as Error).message);}finally{if(version===checkVersion.current)setLoading(false);}}
 useEffect(()=>{clearLegacyRecords();void check();const id=setInterval(check,60000);window.addEventListener('focus',check);return()=>{clearInterval(id);window.removeEventListener('focus',check);checkVersion.current++;};},[]);
 if(loading)return <main className="p-12 text-center">Checking dashboard access…</main>;
 if(!session)return <main className="min-h-screen bg-slate-50 flex items-center justify-center p-5"><form className="w-full max-w-sm rounded-2xl bg-white border p-6 space-y-5 shadow-sm" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),b=await r.json();if(!r.ok)throw Error(b.error);setPassword('');client.clear();await check();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h1 className="text-2xl font-bold">HR dashboard</h1><p className="text-sm text-slate-500">Sign in with your Admin, CEO or HR account.</p><label className="block text-sm">Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full border rounded-lg p-3"/></label><label className="block text-sm">Password<input type="password" autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full border rounded-lg p-3"/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-lg bg-slate-900 text-white p-3 disabled:opacity-50">{busy?'Signing in…':'Sign in'}</button></form></main>;
 const activeView=session.role==='hr'?'interns':view;
 const navigation=<nav aria-label="Employee group" className="flex gap-1 rounded-xl bg-slate-800/80 p-1">
  {(session.role==='hr'?[{id:'interns',label:'Interns',Icon:GraduationCap}]:[{id:'leave',label:'Full-time',Icon:Users},{id:'interns',label:'Interns',Icon:GraduationCap}]).map(({id,label,Icon})=><button key={id} aria-pressed={activeView===id} onClick={()=>setView(id)} className={`flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold transition-colors focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300 ${activeView===id?'bg-cyan-500 text-slate-950 shadow-sm':'text-slate-300 hover:bg-slate-700 hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>)}
 </nav>;
 const account=<DropdownMenu><DropdownMenuTrigger asChild><button className="flex items-center gap-2 rounded-xl border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800" aria-label="Account menu"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-700 font-bold uppercase">{session.username[0]}</span><span className="text-left"><span className="block font-semibold">{session.username}</span><span className="block text-[10px] uppercase tracking-wider text-slate-400">{session.role}</span></span><ChevronDown className="h-4 w-4 text-slate-400"/></button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel>Signed in as {session.username}</DropdownMenuLabel><DropdownMenuSeparator/>{session.role==='admin'&&<DropdownMenuItem onSelect={()=>setView('accounts')}><Settings className="mr-2 h-4 w-4"/>Manage accounts</DropdownMenuItem>}<DropdownMenuItem disabled={busy} onSelect={async()=>{checkVersion.current++;setBusy(true);try{const r=await fetch('/api/auth',{method:'DELETE'});if(!r.ok)throw Error('Sign out failed. Please retry.');client.clear();clearLegacyRecords();setSession(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><LogOut className="mr-2 h-4 w-4"/>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
 return <div className="min-h-screen bg-slate-100 text-slate-900">{error&&<p role="alert" className="bg-red-50 px-5 py-2 text-sm text-red-700">{error}</p>}{activeView==='leave'?<CeoDashboard navigation={navigation} account={account}/>:<><DashboardHeader navigation={navigation} account={account}/>{activeView==='accounts'&&session.role==='admin'?<AccountManager onSaved={check}/>:<InternDashboard canClassify={session.role!=='hr'}/>}</>}</div>;
}
