import {useEffect,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
type Registration={user_id:string;first_name:string;last_name:string;department:string;employment_type:'intern'|'employee'};
export default function RegistrationReview(){
 const [rows,setRows]=useState<Registration[]>([]),[selected,setSelected]=useState<Registration|null>(null),[months,setMonths]=useState(4),[start,setStart]=useState(''),[end,setEnd]=useState(''),[annual,setAnnual]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const client=useQueryClient();
 async function load(){const r=await fetch('/api/registration?review=1',{cache:'no-store'}),b=await r.json();if(!r.ok)throw Error(b.error);setRows(b.registrations);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 return <section className="rounded-2xl border bg-white p-5 space-y-4"><div className="flex justify-between items-center"><h2 className="font-bold">Registrations <span className="text-slate-400">{rows.length}</span></h2><button onClick={()=>load().catch(e=>setError(e.message))} className="text-sm text-cyan-700">Refresh</button></div>{error&&<p role="alert" className="text-red-700">{error}</p>}{!rows.length&&<p className="text-sm text-slate-500">No registrations awaiting review.</p>}{rows.map(r=><div key={r.user_id} className="flex items-center gap-4 border-t pt-3"><div className="mr-auto"><p className="font-semibold">{r.first_name} {r.last_name}</p><p className="text-sm text-slate-500">{r.department} · {r.employment_type==='intern'?'Intern':'Full-time'}</p></div><button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>{setSelected(r);setStart('');setEnd('');setAnnual('');setError('');}}>Review</button></div>)}{selected&&<form className="border-t pt-4 space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/registration',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:selected.user_id,...(selected.employment_type==='intern'?{months,startDate:start,endDate:end}:{annualTotal:Number(annual)})})}),b=await r.json();if(!r.ok)throw Error(b.error);setSelected(null);await load();await client.invalidateQueries({queryKey:['employees']});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h3 className="font-semibold">Activate {selected.first_name}</h3>{selected.employment_type==='intern'?<div className="grid sm:grid-cols-3 gap-3"><label className="text-sm">Programme<select className="block w-full border rounded-lg p-2 mt-1" value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={4}>4 months</option><option value={6}>6 months</option></select></label><label className="text-sm">Start date<input required type="date" className="block border rounded-lg p-2 mt-1 w-full" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">End date<input required type="date" min={start} className="block border rounded-lg p-2 mt-1 w-full" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>:<label className="block text-sm">Annual allowance for this year<input required type="number" min="0" max="366" step="0.25" className="block border rounded-lg p-2 mt-1" value={annual} onChange={e=>setAnnual(e.target.value)}/></label>}<div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-cyan-600 text-white px-4 py-2 disabled:opacity-50">{busy?'Activating…':'Activate profile'}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancel</button></div></form>}</section>;
}
